# Generated by Django 3.0.6 on 2020-06-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_humidityupdation'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_update', models.CharField(max_length=100)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
