# Generated by Django 3.0.6 on 2020-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_temparature_value', models.IntegerField()),
                ('present_temparature_value', models.IntegerField()),
                ('sprinkler_state', models.CharField(max_length=100)),
                ('previous_humidity_value', models.IntegerField()),
                ('present_humidity_value', models.IntegerField()),
                ('water_pump_state', models.CharField(max_length=100)),
                ('street_light_state', models.CharField(max_length=100)),
                ('alarm_state', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_phone', models.IntegerField()),
                ('u_date', models.DateTimeField(auto_now=True)),
                ('u_rate', models.IntegerField()),
                ('u_suggestion', models.TextField()),
                ('u_review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Humidityupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Humidity_status', models.IntegerField()),
                ('Humiditysensorstate', models.BooleanField(default=False)),
                ('Parklocation', models.CharField(max_length=100)),
                ('Review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('EmailId', models.CharField(max_length=100)),
                ('Complaints', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Sensorstatesupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Temp_status', models.IntegerField()),
                ('Tempsensorstate', models.BooleanField(default=False)),
                ('Parklocation', models.CharField(max_length=100)),
                ('Review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sprinklerstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_temparature_value', models.IntegerField()),
                ('present_temparature_value', models.IntegerField()),
                ('sprinkler_state', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Streetlightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_update', models.CharField(max_length=100)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
