# Generated by Django 3.0.6 on 2020-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidityupdation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_humidity_value', models.IntegerField()),
                ('present_humidity_value', models.IntegerField()),
                ('water_state', models.CharField(max_length=100)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
